### PR TITLE
Content added when metamask not connected

### PR DESCRIPTION
**Pull request by kirtilodha**
[GH-122]
https://github.com/Shikhar15606/ElectionDapp/issues/122
Capture

### CODE REVIEW

**Comment by Shikhar15606** [comment]
Hi @kirtilodha, The PR looks good :), but there are a few issues:
1. Since you have modified the test so you need to alter the test written for this component as well. (Just editing the Loading web3 and replacing it with some part of the text you wrote will do the job). Then try testing it locally using yarn test in client folder
https://github.com/Shikhar15606/ElectionDapp/blob/0fd7c0dffcbe30aac1acdc4373657f02c11cac56/client/src/__test__/App.test.js#L20
2. Try to correct the formatting by running the command in the root folder
```
yarn pfix
```
3. Centering the div of the entire content (the new page) that you added will look good
4. Try installing the dependencies using yarn (remove the package-lock.json as well), (I forgot to write that in readme).

**Comment by Shikhar15606** [comment]
> @Shikhar15606 can you check please?
Everything looks good, just run yarn pfix to fix the failing check

**Review by Shikhar15606 — APPROVED** [review]
Great work @kirtilodha! LGTM

@Abhishek357 PTAL

**Review by Abhishek357 — COMMENTED** [review]
Awesome work @kirtilodha :100: :boom:

**Review by Abhishek357 — APPROVED** [review]

**Pull request merged**
